SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM (SELECT BOOK_ID, SUM(SALES) AS SALES 
      FROM BOOK_SALES 
      WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
      GROUP BY BOOK_ID) AS S 
JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_NAME, CATEGORY
ORDER BY A.AUTHOR_ID ASC, CATEGORY DESC