SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
    LEFT JOIN ANIMAL_OUTS O 
        ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE 
    SEX_UPON_OUTCOME IS NOT NULL
ORDER BY
    DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2