SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER, COUNT(DISTINCT U.USER_ID)
FROM USER_INFO AS U JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
