# SELECT 
#     YEAR(SALES_DATE) AS YEAR, 
#     MONTH(SALES_DATE) AS MONTH, 
#     COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
#     ROUND(COUNT(DISTINCT U.USER_ID) / COUNT(*), 1) AS PURCHASED_RATIO
# FROM (
#     SELECT *
#     FROM USER_INFO
#     WHERE YEAR(JOINED) = 2021
# ) AS U
# LEFT JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID
# GROUP BY YEAR, MONTH
# ORDER BY YEAR ASC, MONTH ASC

SELECT 
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM USER_INFO AS U
JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;