WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E2.ID, E2.PARENT_ID, E1.GENERATION + 1
    FROM CTE E1 JOIN ECOLI_DATA E2 ON E1.ID = E2.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM CTE
WHERE ID NOT IN (SELECT PARENT_ID FROM CTE WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION ASC