WITH RECURSIVE DEF AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM DEF
    WHERE HOUR < 23
)

SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM (SELECT HOUR(DATETIME) AS HOUR, ANIMAL_ID
     FROM ANIMAL_OUTS
     UNION ALL
     SELECT HOUR, NULL AS ANIMAL_ID
     FROM DEF
     ) AS A
GROUP BY HOUR
ORDER BY HOUR