WITH CTE AS (
    SELECT USER_ID, NICKNAME, SUM(PRICE) OVER (PARTITION BY USER_ID) AS TOTAL_SALES
    FROM USED_GOODS_BOARD AS B
    JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
    WHERE STATUS = 'DONE'
)

SELECT DISTINCT USER_ID, NICKNAME, TOTAL_SALES
FROM CTE
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC