SELECT E.EMP_NO, E.EMP_NAME,
    CASE WHEN SCORE >= 96 THEN 'S'
    WHEN SCORE >= 90 THEN 'A'
    WHEN SCORE >= 80 THEN 'B'
    ELSE 'C'
    END AS GRADE,
    CASE WHEN SCORE >= 96 THEN SAL * 0.2
    WHEN SCORE >= 90 THEN SAL * 0.15
    WHEN SCORE >= 80 THEN SAL * 0.1
    ELSE 0
    END AS BONUS
FROM HR_DEPARTMENT AS D
JOIN HR_EMPLOYEES AS E ON D.DEPT_ID = E.DEPT_ID
JOIN (SELECT EMP_NO, YEAR, AVG(SCORE) AS SCORE FROM HR_GRADE GROUP BY EMP_NO, YEAR) AS G ON E.EMP_NO = G.EMP_NO
ORDER BY EMP_NO ASC