SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM REST_REVIEW AS R LEFT JOIN MEMBER_PROFILE AS M ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) AS A
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC