SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS R
    JOIN CAR_RENTAL_COMPANY_CAR AS C
        ON R.CAR_ID = C.CAR_ID
WHERE 
    CAR_TYPE = '세단'
    AND MONTH(START_DATE) = 10
ORDER BY
    C.CAR_ID DESC